### ISSUE TITLE
Missing a parenthesis in the Creative Decision Rating (CDR) formula 

### ISSUE THREAD

**Issue by juancamilocampos** [ML-KULeuven/un-xPass#2]
Based on the article, the CDR formula is:
$CDR(D = l|S) = E [U(D = l|S)] - E[U(D= l_{typical}|S)$
which is basically the value of the real pass minus the value of the typical pass. When you decompose the formula you get 

$$CDR(D = l|S)  = P(O = o^{+} |D= l, S) \cdot Q(S|D = l,O = o^{+}) + (1-P(O = o^{+} |D= l, S)) \cdot Q(S|D = l,O = o^{-}) - ($$

$$ \\hspace{2.0em} \\hspace{2.0em} \\hspace{2.0em} P(O = o^{+} |D=  l_{typical}, S) \cdot Q(S|D =  l_{typical},O = o^{+}) + (1-P(O = o^{+} |D= l_{typical}, S)) \cdot Q(S|D =  l_{typical},O = o^{-}))$$

Then, the implementation of the CDR formula is:
```python
df_ratings["CDR"] = (
   df_ratings["true_p_success"] * df_ratings["true_value_success"]
            + (1 - df_ratings["true_p_success"]) * df_ratings["true_value_fail"]
            - (
                    df_ratings["typical_p_success"] * df_ratings["typical_value_success"]
                    + (1 - df_ratings["typical_p_success"]) * df_ratings["typical_value_fail"]
                )
        )
```
This suggest that there is a missing parenthesis in the implementation of this formula in lines https://github.com/ML-KULeuven/un-xPass/blob/aaa9f9476ac61982c9fd5230da9c05715348f3af/unxpass/ratings.py#L116C1-L121C10

**Comment by probberechts** [comment]
Great catch. Thanks!
